import { Vegetable } from './models/models';

export const vegetablesFixture: Vegetable[] = [
  {
    name: 'Tomate',
    description:
      'Plante fruitière très populaire, nécessite beaucoup de lumière et de chaleur.',
    caracteristiques: [
      'Besoin ensoleillement élevé',
      'Sensible au mildiou',
      'Croissance verticale',
    ],
    semis: ['février', 'mars', 'avril'],
    plantation: ['avril', 'mai', 'juin'],
    recolte: ['juillet', 'août', 'septembre', 'octobre'],
    affinites: ['Basilic', 'Carotte', 'Oignon'],
    mauvais_voisins: ['Pomme de terre', 'Fenouil'],
  },
  {
    name: 'Basilic',
    description:
      "Herbe aromatique facile à cultiver, aime la chaleur et l'humidité.",
    caracteristiques: [
      'Aime la chaleur',
      'Pousse rapide',
      'Aromatique puissante',
    ],
    semis: ['mars', 'avril', 'mai'],
    plantation: ['mai', 'juin'],
    recolte: ['juin', 'juillet', 'août', 'septembre'],
    affinites: ['Tomate', 'Poivron', 'Aubergine'],
    mauvais_voisins: ['Rue officinale'],
  },
  {
    name: 'Persil',
    description:
      'Herbe aromatique résistante, pousse bien en intérieur ou extérieur.',
    caracteristiques: [
      'Pousse lente',
      'Résistant au froid',
      'Aromatique universel',
    ],
    semis: ['février', 'mars', 'avril', 'mai', 'juin', 'juillet', 'août'],
    plantation: ['avril', 'mai', 'juin', 'juillet', 'août', 'septembre'],
    recolte: [
      'mai',
      'juin',
      'juillet',
      'août',
      'septembre',
      'octobre',
      'novembre',
    ],
    affinites: ['Tomate', 'Carotte', 'Ciboulette'],
    mauvais_voisins: ['Laitue', 'Menthe'],
  },
  {
    name: 'Laitue',
    description: 'Légume-feuille rapide, aime les zones fraîches et ombragées.',
    caracteristiques: [
      'Croissance rapide',
      'Sensible à la chaleur',
      'Feuillage tendre',
    ],
    semis: [
      'février',
      'mars',
      'avril',
      'mai',
      'juin',
      'juillet',
      'août',
      'septembre',
      'octobre',
    ],
    plantation: [
      'mars',
      'avril',
      'mai',
      'juin',
      'juillet',
      'août',
      'septembre',
      'octobre',
    ],
    recolte: [
      'avril',
      'mai',
      'juin',
      'juillet',
      'août',
      'septembre',
      'octobre',
      'novembre',
    ],
    affinites: ['Radis', 'Carotte', 'Fraise'],
    mauvais_voisins: ['Persil'],
  },
  {
    name: 'Ciboulette',
    description: 'Plante vivace au goût fin, idéale en pot ou pleine terre.',
    caracteristiques: ['Vivace', 'Aime la mi-ombre', 'Anti-insectes'],
    semis: ['mars', 'avril', 'mai'],
    plantation: ['avril', 'mai', 'juin'],
    recolte: [
      'avril',
      'mai',
      'juin',
      'juillet',
      'août',
      'septembre',
      'octobre',
    ],
    affinites: ['Carotte', 'Persil', 'Pommier'],
    mauvais_voisins: ['Haricot'],
  },
  {
    name: 'Menthe',
    description: 'Aromatique vigoureuse, à cultiver de préférence en pot.',
    caracteristiques: ['Invasive', 'Vivace', 'Rafraîchissante'],
    semis: ['mars', 'avril', 'mai'],
    plantation: ['avril', 'mai', 'juin'],
    recolte: ['mai', 'juin', 'juillet', 'août', 'septembre', 'octobre'],
    affinites: ['Chou', 'Pois', 'Radis'],
    mauvais_voisins: ['Persil', 'Camomille'],
  },
];
